npmScopes:
    'awesome.me':
        npmRegistryServer: 'https://npm.fontawesome.com/'
        npmAuthToken: '26BBC255-A14F-4479-B6BF-5FB735BA3579'
    fortawesome:
        npmRegistryServer: 'https://npm.fontawesome.com/'
        npmAuthToken: '26BBC255-A14F-4479-B6BF-5FB735BA3579'
